"""MCA language specification exporter.

Generates a machine-readable JSON spec from Python runtime definitions.
This is the bridge between the Python implementation (single source of truth)
and all consumers (VS Code language server, tests, tooling).

Usage:
    from core.mca_spec import export_spec
    spec = export_spec()
"""

from __future__ import annotations

from typing import Any

from core.api.services.actions import TRIGGER_TYPE_MAP
from core.mca_parser import EVENT_TRIGGERS
from core.validator import (
    _RE_DYNAMIC_VANILLA,
    _RE_INVALID_MULTIPLIER,
    _RE_MULTIPLIER,
    _RE_OVERLAY_PREFIX,
    _RE_TRAILING_SEMICOLON,
    COMMAND_PREFIX_CHARS,
    DIAGNOSTIC_CODES,
    HIGH_MULTI_THRESHOLD,
)


def export_spec() -> dict[str, Any]:
    """Build the complete MCA language specification dict from runtime data.

    Returns:
        A dict matching the mca-spec.json schema. All values are derived
        directly from the Python runtime (validator.py, actions.py).
    """
    event_triggers = sorted(EVENT_TRIGGERS)

    command_prefixes = _build_command_prefixes()

    patterns = {
        "trailing_semicolon": _RE_TRAILING_SEMICOLON.pattern,
        "overlay_prefix": _RE_OVERLAY_PREFIX.pattern,
        "multiplier": _RE_MULTIPLIER.pattern,
        "invalid_multiplier": _RE_INVALID_MULTIPLIER.pattern,
        "dynamic_vanilla": _RE_DYNAMIC_VANILLA.pattern,
    }

    validation_rules = {
        "high_multi_threshold": HIGH_MULTI_THRESHOLD,
        "allow_comment_placeholder_on": ["comment"],
        "valid_unquoted_trigger": r"^[A-Za-z0-9_]+$",
        "valid_quoted_trigger": r"^'[A-Za-z0-9_ ]+'$",
        "disabled_prefix": "##",
        "comment_prefix": "#",
        "inline_comment_char": "#",
        "command_separator": ";",
        "trigger_colon": ":",
        "multiplier_prefix": "x",
    }

    command_start_patterns = {
        "single_char": list(COMMAND_PREFIX_CHARS),
        "multi_char": [">>"],
        "named_overlay": "@name>>",
        "description": "Commands must start with /, !, $, &, >>, or @name>>",
    }

    diagnostic_codes = [
        {"code": code, "severity": info.severity, "message": info.message}
        for code, info in sorted(DIAGNOSTIC_CODES.items())
    ]

    spec: dict[str, Any] = {
        "_comment": "AUTO-GENERATED by src/core/mca_spec.py. DO NOT EDIT.",
        "version": "1.0",
        "generated_by": "src/core/mca_spec.py",
        "generated_from": [
            "src/core/validator.py",
            "src/core/api/services/actions.py",
        ],
        "event_triggers": event_triggers,
        "event_trigger_docs": _EVENT_TRIGGER_DOCS,
        "command_prefixes": command_prefixes,
        "command_start_patterns": command_start_patterns,
        "patterns": patterns,
        "validation_rules": validation_rules,
        "diagnostic_codes": diagnostic_codes,
        "placeholders": _PLACEHOLDERS,
    }

    return spec


def _build_command_prefixes() -> dict[str, dict[str, str]]:
    """Build command prefix metadata from runtime data."""
    prefixes: dict[str, dict[str, str]] = {}

    for ch, type_name in sorted(TRIGGER_TYPE_MAP.items()):
        prefixes[ch] = {
            "type": type_name,
            "label": _PREFIX_LABELS.get(type_name, type_name.title()),
            "doc": _PREFIX_DOCS.get(ch, ""),
        }

    # Overlay is handled at the language level but not in TRIGGER_TYPE_MAP
    prefixes[">>"] = {
        "type": "overlay",
        "label": "Overlay",
        "doc": _PREFIX_DOCS.get(">>", ""),
    }

    return prefixes


# -- Language metadata (descriptive, not used by runtime logic) --------------

_PREFIX_LABELS: dict[str, str] = {
    "vanilla": "Vanilla Minecraft",
    "rcon": "RCON",
    "script": "Script",
    "shell": "Shell",
}

_PREFIX_DOCS: dict[str, str] = {
    "/": (
        "Minecraft command executed via datapack .mcfunction files. "
        "The command body (after /) is written to a .mcfunction file "
        "and invoked via /function namespace:triggername. "
        "Add ' !rc' suffix to send via RCON instead, enabling {user} substitution."
    ),
    "!": (
        "RCON-only command sent directly to the Minecraft server "
        "via the RCON protocol. Not written to the datapack."
    ),
    "$": (
        "Hook script action. The name after $ is looked up in the "
        "HOOK_ACTIONS registry and the registered Python handler "
        "is called. Built-in: $random."
    ),
    "&": (
        "Shell command executed on the host PC via subprocess. "
        "{user} is NOT replaced in shell commands \u2014 they receive "
        "the raw body from the MCA file."
    ),
    ">>": (
        "Overlay text. Syntax: >>Title|Subtitle|Duration. "
        "Parts are pipe-separated. Only Title is required. "
        "Duration defaults to 3 seconds if omitted or non-numeric. "
        "{user} and {comment} are replaced."
    ),
}

_EVENT_TRIGGER_DOCS: list[dict[str, str]] = [
    {"name": "follow", "doc": "Fires when someone follows the stream."},
    {"name": "join", "doc": "Fires when someone joins the stream."},
    {
        "name": "comment",
        "doc": (
            "Fires when someone sends a chat comment. "
            "This is the only trigger that supports the {comment} placeholder."
        ),
    },
    {
        "name": "likes",
        "doc": (
            "Fires every N likes (configurable in config.yaml). "
            "Default interval is 100 likes."
        ),
    },
    {
        "name": "like_2",
        "doc": "Fires at a bigger milestone (default: 100_000 likes).",
    },
    {"name": "share", "doc": "Fires when someone shares the stream."},
]

_PLACEHOLDERS: list[dict[str, Any]] = [
    {
        "name": "{user}",
        "triggers": ["all"],
        "doc": (
            "Replaced with the triggering user's display name. "
            "Available on all triggers."
        ),
    },
    {
        "name": "{comment}",
        "triggers": ["comment"],
        "doc": (
            "Replaced with comment text. "
            "Only works on the 'comment' trigger. "
            "Using it elsewhere produces a validation error."
        ),
    },
]
